# @name GetPrompts
GET http://localhost:3333/prompts

###

# @name uploadVideos
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name createTranscription
POST http://localhost:3333/videos/94f803f5-c97b-491f-bf87-945912314215/transcription
Content-Type: application/json

{
  "prompt": "Olá, gravação, voz"
}

###

# @name generateAICompletion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "94f803f5-c97b-491f-bf87-945912314215",
  "temperature": 0.5,
  "prompt": "Disserte a transcrição do vídeo informada a seguir: '''{transcription}'''"
}